### ISSUE TITLE
前端显示问题

### ISSUE THREAD

**Issue by zfdx123** [muzi9527/baiduwp-springboot#1]
本工程在后端运行日志中打印了所有数据信息，但前端只返回了一个1

**Comment by muzi9527** [comment]
呃呃，一直都有这个问题，这源码写了好久了，很多地方可以优化，我找个时间重构一下，写个JsonResponse

**Comment by muzi9527** [comment]
> 本工程在后端运行日志中打印了所有数据信息，但前端只返回了一个1

呃呃，一直都有这个问题，这二进制写了了好久了，很多地方可以优化，我找个时间重构一下，写个JsonResponse。

**Comment by zfdx123** [comment]
加油
